import React, {
  createContext,
  useCallback,
  useContext,
  useMemo,
} from "react";
import { useSettings } from "./SettingsContext";

const english = {
  accountControl: "Account Control",
  actions: "Actions",
  addBudget: "Add Budget",
  addTransaction: "Add Transaction",
  addUser: "Add User",
  adminConsole: "Admin Console",
  adminUsers: "Admin Users",
  analytics: "Analytics",
  analyticsOverview: "Analytics Overview",
  annualIncome: "Annual Income",
  appearance: "Appearance",
  appNotifications: "App Notifications",
  autoSave: "Auto Save",
  balance: "Balance",
  budget: "Budget",
  budgetHealth: "Budget Health",
  budgetLimit: "Budget Limit",
  budgetPlanner: "Budget Planner",
  calculator: "Calculator",
  category: "Category",
  changePassword: "Change Password",
  confirmPassword: "Confirm Password",
  createAccount: "Create Account",
  currentBalance: "Current Balance",
  currentPassword: "Current Password",
  dashboard: "Dashboard",
  dark: "Dark",
  darkMode: "Dark Mode",
  deductions: "Deductions",
  delete: "Delete",
  downloadPdf: "Download PDF",
  edit: "Edit",
  email: "Email",
  emailAddress: "Email Address",
  estimatedTax: "Estimated Tax",
  expenses: "Expenses",
  financeAnalytics: "Finance Analytics",
  financeDashboard: "Finance Dashboard",
  financeOverview: "Finance Overview",
  financialOverview: "Financial Overview",
  forgotPassword: "Forgot Password",
  fullName: "Full Name",
  googleUnavailable: "Google Sign-In is not configured for this environment.",
  healthy: "Healthy",
  helpGuidance: "Help & Guidance",
  high: "High",
  income: "Income",
  interfaceLanguage: "Interface Language",
  left: "Left",
  light: "Light",
  limit: "Limit",
  loading: "Loading",
  loginSubtitle: "Login to continue to TaxPal",
  logout: "Logout",
  mode: "Mode",
  monthlyBudget: "Monthly Budget",
  monthlyBudgetOverview: "Monthly Budget Overview",
  name: "Name",
  netIncome: "Net Income",
  newPassword: "New Password",
  notifications: "Notifications",
  password: "Password",
  preferences: "Preferences",
  privacy: "Privacy",
  privacyMode: "Privacy Mode",
  profile: "Profile",
  progress: "Progress",
  remaining: "Remaining",
  resetPassword: "Reset Password",
  role: "Role",
  saveProfile: "Save Profile",
  savingsGoal: "Savings Goal",
  searchUsers: "Search users by name...",
  security: "Security",
  sendResetLink: "Send Reset Link",
  setNewBudget: "Set New Budget",
  settings: "Settings",
  signIn: "Sign In",
  signUp: "Sign Up",
  sound: "Sound",
  soundEffects: "Sound Effects",
  spent: "Spent",
  startPage: "Start Page",
  systemNotifications: "System Notifications",
  tax: "Tax",
  taxDashboard: "Tax Dashboard",
  taxPlanning: "Tax Planning",
  taxSavingSuggestions: "Tax Saving Suggestions",
  taxSlabs: "Tax Slabs",
  taxableIncome: "Taxable Income",
  theme: "Theme",
  totalExpense: "Total Expense",
  totalIncome: "Total Income",
  totalUsers: "Total Users",
  transactions: "Transactions",
  transactionsTitle: "Transactions",
  users: "Users",
  usersManagement: "Users Management",
  visibleResults: "Visible Results",
  welcomeBack: "Welcome Back",
  workspaceBehavior: "Workspace Behavior",
};

export const translations = {
  English: english,
  Tamil: {
    ...english,
    accountControl: "கணக்கு கட்டுப்பாடு",
    actions: "செயல்கள்",
    addBudget: "பட்ஜெட் சேர்",
    addTransaction: "பரிவர்த்தனை சேர்",
    addUser: "பயனர் சேர்",
    adminConsole: "நிர்வாக பலகம்",
    adminUsers: "நிர்வாக பயனர்கள்",
    analytics: "பகுப்பாய்வு",
    analyticsOverview: "பகுப்பாய்வு பார்வை",
    annualIncome: "ஆண்டு வருமானம்",
    appearance: "தோற்றம்",
    appNotifications: "செயலி அறிவிப்புகள்",
    autoSave: "தானாக சேமி",
    balance: "இருப்பு",
    budget: "பட்ஜெட்",
    budgetHealth: "பட்ஜெட் நிலை",
    budgetLimit: "பட்ஜெட் வரம்பு",
    budgetPlanner: "பட்ஜெட் திட்டமிடல்",
    calculator: "கணிப்பான்",
    category: "வகை",
    changePassword: "கடவுச்சொல் மாற்று",
    confirmPassword: "கடவுச்சொல் உறுதி",
    createAccount: "கணக்கு உருவாக்கு",
    currentBalance: "தற்போதைய இருப்பு",
    currentPassword: "தற்போதைய கடவுச்சொல்",
    dashboard: "டாஷ்போர்டு",
    dark: "இருள்",
    darkMode: "இருள் முறை",
    deductions: "கழிவுகள்",
    delete: "நீக்கு",
    downloadPdf: "PDF பதிவிறக்கு",
    edit: "திருத்து",
    email: "மின்னஞ்சல்",
    emailAddress: "மின்னஞ்சல் முகவரி",
    estimatedTax: "மதிப்பிடப்பட்ட வரி",
    expenses: "செலவுகள்",
    financeAnalytics: "நிதி பகுப்பாய்வு",
    financeDashboard: "நிதி டாஷ்போர்டு",
    financeOverview: "நிதி பார்வை",
    financialOverview: "நிதி பார்வை",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா",
    fullName: "முழு பெயர்",
    googleUnavailable: "இந்த சூழலில் Google உள்நுழைவு அமைக்கப்படவில்லை.",
    healthy: "சீரானது",
    helpGuidance: "உதவி மற்றும் வழிகாட்டல்",
    high: "அதிகம்",
    income: "வருமானம்",
    interfaceLanguage: "இடைமுக மொழி",
    left: "மீதம்",
    light: "ஒளி",
    limit: "வரம்பு",
    loading: "ஏற்றுகிறது",
    loginSubtitle: "TaxPal-ஐ தொடர உள்நுழைக",
    logout: "வெளியேறு",
    mode: "முறை",
    monthlyBudget: "மாதாந்திர பட்ஜெட்",
    monthlyBudgetOverview: "மாதாந்திர பட்ஜெட் பார்வை",
    name: "பெயர்",
    netIncome: "நிகர வருமானம்",
    newPassword: "புதிய கடவுச்சொல்",
    notifications: "அறிவிப்புகள்",
    password: "கடவுச்சொல்",
    preferences: "விருப்பங்கள்",
    privacy: "தனியுரிமை",
    privacyMode: "தனியுரிமை முறை",
    profile: "சுயவிவரம்",
    progress: "முன்னேற்றம்",
    remaining: "மீதமுள்ளது",
    resetPassword: "கடவுச்சொல் மீட்டமை",
    role: "பங்கு",
    saveProfile: "சுயவிவரத்தை சேமி",
    savingsGoal: "சேமிப்பு இலக்கு",
    searchUsers: "பெயரால் பயனர்களை தேடுங்கள்...",
    security: "பாதுகாப்பு",
    sendResetLink: "மீட்டமைப்பு இணைப்பு அனுப்பு",
    setNewBudget: "புதிய பட்ஜெட் அமை",
    settings: "அமைப்புகள்",
    signIn: "உள்நுழை",
    signUp: "பதிவு செய்",
    sound: "ஒலி",
    soundEffects: "ஒலி விளைவுகள்",
    spent: "செலவிட்டது",
    startPage: "தொடக்க பக்கம்",
    systemNotifications: "கணினி அறிவிப்புகள்",
    tax: "வரி",
    taxDashboard: "வரி டாஷ்போர்டு",
    taxPlanning: "வரி திட்டமிடல்",
    taxSavingSuggestions: "வரி சேமிப்பு பரிந்துரைகள்",
    taxSlabs: "வரி அடுக்குகள்",
    taxableIncome: "வரி விதிக்கத்தக்க வருமானம்",
    theme: "தீம்",
    totalExpense: "மொத்த செலவு",
    totalIncome: "மொத்த வருமானம்",
    totalUsers: "மொத்த பயனர்கள்",
    transactions: "பரிவர்த்தனைகள்",
    transactionsTitle: "பரிவர்த்தனைகள்",
    users: "பயனர்கள்",
    usersManagement: "பயனர் மேலாண்மை",
    visibleResults: "காணும் முடிவுகள்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    workspaceBehavior: "பணியிட நடத்தை",
  },
  Hindi: {
    ...english,
    accountControl: "खाता नियंत्रण",
    actions: "कार्रवाई",
    addBudget: "बजट जोड़ें",
    addTransaction: "लेन-देन जोड़ें",
    addUser: "उपयोगकर्ता जोड़ें",
    adminConsole: "एडमिन कंसोल",
    adminUsers: "एडमिन उपयोगकर्ता",
    analytics: "विश्लेषण",
    analyticsOverview: "विश्लेषण अवलोकन",
    annualIncome: "वार्षिक आय",
    appearance: "दिखावट",
    appNotifications: "ऐप सूचनाएं",
    autoSave: "स्वतः सहेजें",
    balance: "शेष राशि",
    budget: "बजट",
    budgetHealth: "बजट स्थिति",
    budgetLimit: "बजट सीमा",
    budgetPlanner: "बजट योजना",
    calculator: "कैलकुलेटर",
    category: "श्रेणी",
    changePassword: "पासवर्ड बदलें",
    confirmPassword: "पासवर्ड पुष्टि करें",
    createAccount: "खाता बनाएं",
    currentBalance: "वर्तमान शेष",
    currentPassword: "वर्तमान पासवर्ड",
    dashboard: "डैशबोर्ड",
    dark: "डार्क",
    darkMode: "डार्क मोड",
    deductions: "कटौतियां",
    delete: "हटाएं",
    downloadPdf: "PDF डाउनलोड करें",
    edit: "संपादित करें",
    email: "ईमेल",
    emailAddress: "ईमेल पता",
    estimatedTax: "अनुमानित कर",
    expenses: "खर्च",
    financeAnalytics: "वित्तीय विश्लेषण",
    financeDashboard: "वित्त डैशबोर्ड",
    financeOverview: "वित्त अवलोकन",
    financialOverview: "वित्तीय अवलोकन",
    forgotPassword: "पासवर्ड भूल गए",
    fullName: "पूरा नाम",
    googleUnavailable: "इस वातावरण में Google साइन-इन कॉन्फिगर नहीं है।",
    healthy: "स्वस्थ",
    helpGuidance: "सहायता और मार्गदर्शन",
    high: "उच्च",
    income: "आय",
    interfaceLanguage: "इंटरफेस भाषा",
    left: "बचा",
    light: "लाइट",
    limit: "सीमा",
    loading: "लोड हो रहा है",
    loginSubtitle: "TaxPal जारी रखने के लिए लॉगिन करें",
    logout: "लॉगआउट",
    mode: "मोड",
    monthlyBudget: "मासिक बजट",
    monthlyBudgetOverview: "मासिक बजट अवलोकन",
    name: "नाम",
    netIncome: "शुद्ध आय",
    newPassword: "नया पासवर्ड",
    notifications: "सूचनाएं",
    password: "पासवर्ड",
    preferences: "प्राथमिकताएं",
    privacy: "गोपनीयता",
    privacyMode: "गोपनीयता मोड",
    profile: "प्रोफाइल",
    progress: "प्रगति",
    remaining: "शेष",
    resetPassword: "पासवर्ड रीसेट करें",
    role: "भूमिका",
    saveProfile: "प्रोफाइल सहेजें",
    savingsGoal: "बचत लक्ष्य",
    searchUsers: "नाम से उपयोगकर्ताओं को खोजें...",
    security: "सुरक्षा",
    sendResetLink: "रीसेट लिंक भेजें",
    setNewBudget: "नया बजट सेट करें",
    settings: "सेटिंग्स",
    signIn: "साइन इन",
    signUp: "साइन अप",
    sound: "ध्वनि",
    soundEffects: "ध्वनि प्रभाव",
    spent: "खर्च हुआ",
    startPage: "आरंभ पृष्ठ",
    systemNotifications: "सिस्टम सूचनाएं",
    tax: "कर",
    taxDashboard: "कर डैशबोर्ड",
    taxPlanning: "कर योजना",
    taxSavingSuggestions: "कर बचत सुझाव",
    taxSlabs: "कर स्लैब",
    taxableIncome: "कर योग्य आय",
    theme: "थीम",
    totalExpense: "कुल खर्च",
    totalIncome: "कुल आय",
    totalUsers: "कुल उपयोगकर्ता",
    transactions: "लेन-देन",
    transactionsTitle: "लेन-देन",
    users: "उपयोगकर्ता",
    usersManagement: "उपयोगकर्ता प्रबंधन",
    visibleResults: "दिखने वाले परिणाम",
    welcomeBack: "वापसी पर स्वागत है",
    workspaceBehavior: "कार्यस्थल व्यवहार",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const {
    settings,
    updateSettings,
    setSettings,
  } = useSettings();

  const language = translations[settings.language]
    ? settings.language
    : "English";

  const labels = translations[language];

  const setLanguage = useCallback((nextLanguage) => {
    setSettings((current) => ({
      ...current,
      language: nextLanguage,
    }));

    updateSettings(
      {
        language: nextLanguage,
      },
      {
        localOnly: true,
        silentSound: true,
      }
    );
  }, [setSettings, updateSettings]);

  const translate = useCallback(
    (key) => labels[key] || translations.English[key] || key,
    [labels]
  );

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      labels,
      t: translate,
      translations,
    }),
    [language, labels, setLanguage, translate]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
};
